### ISSUE TITLE
add travis CI

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#135]
http://conda.pydata.org/docs/travis.html
http://docs.travis-ci.com/user/build-configuration/#Build-Lifecycle
https://github.com/numba/numba/blob/master/.travis.yml

**Comment by benjello** [comment]
Tests handled with nosetest and executed with travis can be found here (many thanks @cbenz):
https://travis-ci.org/benjello/liam2
There is still a pending problem with tables.open_file from python-tables on travis but tests infrastructure runs locally (some tests are buggy though)

**Comment by gdementen** [comment]
Thanks for tackling this. Some quick notes (I'm on holidays so...):
* please make a pull request for this (even if incomplete), it would make reviewing the changes/commenting, easier.
* not very fond of adding a Makefile, that doesn't feel very cross-platform (I know about -- and actually use cygwin & mingw), nor Python-ish
* I should update the liam2/INSTALL, as we apparently require PyTables 3+ now (see your open_file errors).
* those PyTables errors could be solved by using conda (that's what I would do).
* I am a bit hesitant to move the examples to /liam2/tests/examples. Wouldn't they be more discoverable in /examples (or possibly in /doc/examples)? They still would need to be tested though.
* sorry for breaking the setup.py without cxfreeze :)

**Comment by gdementen** [comment]
All of those comments are not decisions set in stone. I am open to discussion!

**Comment by benjello** [comment]
I continue the discussion in the PR [comments] (https://github.com/liam2/liam2/pull/182)

**Comment by gdementen** [comment]
done in #182
