### ISSUE TITLE
Cannot override period type during import

### ISSUE THREAD

**Issue by leonardo-calcagno** [liam2/liam2#154]
This issue makes it impossible to simulate a model with a starting period of 1. When you want to simulate a model with a period named 1, you get an error message stating that the variable period is a boolean. Specifying it is an integer in the fields section before simulation does not solve this. Usually you would solve this by specifying the type of the "period" variable when importing the dataset. But if you want to specify it you get the error message "two fields with the same name", since the period field is automatically added by LIAM2 (which assumes it is a boolean). 
It is a small bug, the workaround being naming your period with any number greater than 1 (since LIAM2 automatically recognises it is an integer when doing so), but still a bug.

**Comment by gdementen** [comment]
The fact the period is considered boolean is normal, because it sees a column with only 1. The fact that you cannot override it is the actual bug.
