### ISSUE TITLE
simulating zero periods fails

### ISSUE THREAD

**Issue by gdekkers** [liam2/liam2#158]
I would like to use LIAM2 for static simulation purposes only, that is, to make changes only to the starting dataset. However, setting periods: 0 results in an error message

Traceback (most recent call last):
  File "main.py", line 38, in eat_traceback
  File "main.py", line 111, in simulate
  File "simulation.py", line 507, in run
ZeroDivisionError: division by zero

Could this be resolved? Thanks

Gijs

**Comment by gdementen** [comment]
Why did you close the issue?

**Comment by gdekkers** [comment]
Dunno…because I do not know what I am doing?

G
