### ISSUE TITLE
Incoherent lag() expressions when removing observations

### ISSUE THREAD

**Issue by leonardo-calcagno** [liam2/liam2#159]
This problem arises when I try to make individuals "younger", that is, make a retrospective simulation. To do so, I do this kind of code: 
            ageing: 
                - agetrimestres: agetrimestres - 1
                - unborn: if(agetrimestres<0, True, False)       
                - age: trunc(agetrimestres/4)
So far, so good, I get normal results when I type in the interactive console 
groupby(age,lag(age)). 
The problem arises when I want to remove people with negative age (that is, people who are not born yet): 
- remove(unborn)
Then I start having incoherent lag data, for instance if age is  10 in the current simulated period, lag(age), instead of being 11 for all these individuals, takes any kind of value, as can be seen in the image below. This does not happen when I do not remove people who are not yet born. 

Is there something I've been doing wrong or is there some kind of bug? 
![bug liam2](https://cloud.githubusercontent.com/assets/7986102/7232250/d616f7dc-e77a-11e4-9ab3-a89ffb995ca2.png)

Thank you in advance, 
Best regards, 
Leonardo Calcagno, University of Orleans

**Comment by gdementen** [comment]
Could you try producing a minimal test case based on the demo model, so that I can reproduce this easier?

**Comment by leonardo-calcagno** [comment]
There, I found the problem, it was in my dataset (there were some lines with missing age, hence having a starting age of -1). After I fixed these lines, the problem disappears.  
Sorry for the trouble and thank you for your advice

**Comment by gdementen** [comment]
No problem, really. You probably hit a bug in an edge case. Whether it is worth fixing or not I cannot tell without understanding what happens and thus having some code to play with. Just tell me if you do not want to do that (that is fine by me) so that I close the issue.

**Comment by leonardo-calcagno** [comment]
It's fine by me, it's not a bug that happens when I input a sound dataset so it shouldn't be a problem later on. If you want to I can still send you the dataset that caused the bug to appear in the first place though.
