### ISSUE TITLE
Add more version tag

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#163]
It would be useful to have all the announced version tagged.
For example it would be nice to have version 0.9.1.1 tagged

**Comment by gdementen** [comment]
It is supposed to be the case. I guess there is a bug in the release script. I'll add the tag for 0.9.1.1 manually and try to fix the script for the next release.

**Comment by gdementen** [comment]
I just tagged 0.9.1.1. I will now investigate why it was not created...

**Comment by gdementen** [comment]
I have hopefully fixed it. We'll see when I'll do the actual release.
