### ISSUE TITLE
get a paramter depending on age and changing with period

### ISSUE THREAD

**Issue by AlexisEidelman** [liam2/liam2#177]
I would like to get a paramater, alpha_i, depending on individuals caracteristics, X_i for all individuals.
The parameters are stored in a csv and change with time.

csv : 
age, 1,2,3,4,5    -> perdiod
0, a01, a02, a03, a04, a05
1, a11, a12, a13, a14, a15
....
T, a1T, a1T, a1T, a1T, a1T

my entity can be someting like : 

id, age, ....
..., 15, ....
..., 0, ....
..., 1, ....
..., 0, ....

and I want, for the period T : 
id, age, a, ....
..., 15, a15T, ....
..., 0, a0T, ....
..., 1, a1T, ....
..., 0, a0T, ....

**Comment by AlexisEidelman** [comment]
a function  : get_value_from_csv ? 
get_value_from_csv('example.csv')

with load_ndarray and a merge ?

**Comment by gdementen** [comment]
Is something preventing you from using normal global arrays?
http://liam2.plan.be/documentation/0.10.2/model.html#globals

You could have one keyed on age/period, and access it using
MYARRAY[age_idx, period_idx]

where age_idx would be simply "age" if your array contains all ages and starts at age 0 and period_idx is the expression giving you the column number to look into (0-based). For example:
period - 1980 if your first data is for 1980.

http://liam2.plan.be/documentation/0.10.2/processes.html#globals

**Comment by benjello** [comment]
Imagine now that you want acces a structure with more dimensions, say:
MYARRAY[age_idx, period_idx, sex]  

Is it possible.
In this cas (sex), I can just have two arrays instead of one, but it might be useful.
Thanks

**Comment by gdementen** [comment]
You can have as many dimensions as you like...

**Comment by benjello** [comment]
Now if I want to creates those files, does something like [this] (http://stackoverflow.com/questions/8843062/python-how-to-store-a-numpy-multidimensional-array-in-pytables) works ?

**Comment by gdementen** [comment]
You can load either load them in the simulation from csv or import them from .csv into the .h5 input during "import". It should be possible to create them outside of LIAM2, but I don't remember if "raw" (without dimensions/pvalues) arrays would work.

If you want to roll your own code instead of going through LIAM2 (please explain me why you want to do that), see https://github.com/liam2/liam2/blob/master/src/importer.py#L472 for loading from CSV and
https://github.com/liam2/liam2/blob/master/src/importer.py#L351 for how to create the H5 file.

**Comment by benjello** [comment]
It tried to use slices as follows:
    
     myvar: MYARRAY[period_idx, 0:120]

but i got erros. Could you confirm that slices are not possible ?
Thanks

**Comment by gdementen** [comment]
I don't see any fundamental reason it shouldn't work but I admit I never tried. So if it does not work, it's a bug. Probably a stupid one.

**Comment by gdementen** [comment]
* @benjello Could you open a separate issue for the slice stuff?
* @AlexisEidelman, @benjello May I close this issue?

**Comment by benjello** [comment]
This issue can be closed. I managed to slice the data.
