### ISSUE TITLE
if(constant, expr1, expr2) breaks

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#185]
There is no numexpr issue tracking this.

See:
https://github.com/pydata/numexpr/blame/master/numexpr/expressions.py#L214

**Comment by benjello** [comment]
Is this fixed ?
Is it possible to use if else statements to trigger some options ?
(didn't try ...)

**Comment by gdementen** [comment]
Nope. Still needs to be fixed in numexpr. Creating an issue for it directly on the numexpr project might help. Fixing the problem would actually be very easy, it just never surfaced at a moment where I had the time to do it.

**Comment by gdementen** [comment]
pydata/numexpr#218

**Comment by benjello** [comment]
@gdementen : this bug is quite annoying and yields us to look for nasty workarounds.
Can't we try to monkey patch numexpr for liam2 for the time being ?

cc @benbel

**Comment by gdementen** [comment]
Why not submit a PR to numexpr? Simply removing the two following lines (the if clause) should work AFAIK. 

```python
if isinstance(a, ConstantNode):
     raise ValueError("too many dimensions")
```

You would also need to add a test in the test suite, but that shouldn't be too hard.

Or if you want to be more efficient, you could try:

```python
if isinstance(a, ConstantNode):
     return b if a.value else c
```
If you submit a PR to numexpr **and** it is not accepted after a while, I can accept a PR in liam2 monkey-patching numexpr for the fix, but you need to first try upstream.

**Comment by benjello** [comment]
see also https://github.com/pydata/numexpr/pull/287

**Comment by benjello** [comment]
The numexpr PR is merged. @gdementen this issue might worth closing after adding a condition on numexpr version in `setup.py`

**Comment by benjello** [comment]
numexpr >= 2.6.6 should do it.

**Comment by gdementen** [comment]
be my guest :)
