### ISSUE TITLE
question: how to log all the yaml used for a run ? 

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#195]
I would like the save logs, data and yaml configuration file for each of my runs by adding method or subclassing the Simulation object. Is the state of `content` at this [line] (https://github.com/liam2/liam2/blob/master/liam2/simulation.py#L218) the place where all the information I am looking for is stored and can be dumped easily in a yaml file ?

**Comment by gdementen** [comment]
Indeed. This is the complete (ie after handling imports) simulation description.
