### ISSUE TITLE
Implement __version__

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#196]
I could add the version number by hand but you may have another way to get the current version.

**Comment by benjello** [comment]
Got it in `liam2.main.__version__`
Isn't  `liam2.__init__`.py a better place ?

**Comment by benjello** [comment]
@gdementen : shoud I implement that or should I forget it ?

**Comment by gdementen** [comment]
Well, __version__ should certainly be available in __init__. But having it defined there or in main.py or in version.py or whatever is fine to me. hmmm, now that I think of it, version.py is probably better because then it can be shared with the setup.py.

**Comment by benjello** [comment]
What about the solution exposed [in the most voted answer here] (http://stackoverflow.com/questions/17583443/what-is-the-correct-way-to-share-package-version-with-setup-py-and-the-package).

**Comment by gdementen** [comment]
I do not like it. Too complicated and does not work in all cases (ie dev version).

**Comment by benjello** [comment]
Got it. Can you find a solution that suits you in [those] (http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/).
Since I spent some time looking for __version__, i thought it was convenient to fix/change it. But we can leave it untouched.

**Comment by gdementen** [comment]
Version 3 seems like the least horrible to me.

On Tue, Dec 22, 2015 at 2:09 PM, Mahdi Ben Jelloul <notifications@github.com
