### ISSUE TITLE
Set value of a global parameter in the yaml file should be possible

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#203]
It doesn't seem possible to assign a value to a global parameter as done below:

``` yaml
globals:
  weight: 200
```

**Comment by gdementen** [comment]
Indeed. For now, globals can only be defined externally (in a .csv or the input .hdf file). This would be a great addition in case you feel like implementing that.

**Comment by benjello** [comment]
I can try it if you tell me where you would start ;-)

**Comment by gdementen** [comment]
the loading should happen in index_tables: https://github.com/liam2/liam2/blob/master/liam2/data.py#L720
You probably want to plug that functionality just before or after load_path_globals
https://github.com/liam2/liam2/blob/master/liam2/data.py#L720

You will probably also need to modify global_symbols in entities.py.

**Comment by benjello** [comment]
Provided by #206
