### ISSUE TITLE
How to save some data when debugging ?

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#204]
What is the best practice for saving some debug data data when debugging and only then.
Should I write macros with a debug argument that do nothing when `debug == false` ?

**Comment by gdementen** [comment]
For .csv, you could use a "csv(dump(filter=xyz and DEBUG), ...) have a DEBUG macro that you flip to True when you want to debug, For show(), there is the skip_shows option, if all shows are used for debugging, you simply use skip_shows: True when you do not.
