### ISSUE TITLE
Charts (Output) functionality

### ISSUE THREAD

**Issue by fostermeijer** [liam2/liam2#209]
Currently it appears the chart functionality is rather limited. 
One issue is that bar graphs are not always comparable because the axes changes depending on the range of data. I have not been able to adjust the axes range and it does not appear to be integrated into the code yet. Is this an easy change?

**Comment by gdementen** [comment]
It is limited indeed. I always planned to revisit it, but never had time to do so...

Adding the following lines to liam2/charts.py@109 seems to do the trick.
```python
        plt.xlim(xmin=kwargs.pop('xmin', None), xmax=kwargs.pop('xmax', None))
        plt.ylim(ymin=kwargs.pop('ymin', None), ymax=kwargs.pop('ymax', None))
```
then using it like:
```python
- bar(byage, ymax=100, fname='bar1.png')
```
If you could make a pull request with this change *and* the corresponding documentation, that would make it easier for me to include it in the next release.
