### ISSUE TITLE
How to add some actions to Notepad menu

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#210]
If i can add a new script similar to main.py how can I call it from Notepad++ menu ?
Where should I look ?

**Comment by gdementen** [comment]
Plugins->NppExec->Execute...
enter your command
then use "Save..." button
then Plugins->NppExec->Advanced Options...
enter menuitem name in the "Item name:" textbox of the "Menu Item" option group (bottom left) and use "Add/Modify" button.

look in nppexec documentation for more info.
