### ISSUE TITLE
use a string or a path as a macro or a global

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#242]
It would be nice to use a string or a path as a macro or a global.
Now if you want to define a string (that you can use as a path), you have to use escape characters as in the following:
````yaml
macros:
     STRING: "\"my string\""
````
which can be cumbersome and error prone.

How could we improve that ? (ready to bring in some manpower if needed ;-))

**Comment by gdementen** [comment]
Unsure we can do anything for macros. Because the point of macros is to be code, so the typed "string" is evaluated, hence the need to escape them. Besides, we need to stay within the boundaries of what yaml allows us to do. However I think string global constants should be doable.

**Comment by gdementen** [comment]
this is done on master
