### ISSUE TITLE
Add support for multiple description files

### ISSUE THREAD

**Issue by benbel** [liam2/liam2#245]
Models can be split into different files, and then each file can be imported by another through the keyword `import`.

As far as I understand, it is not possible to do so with description files: trying to import a file from a 'main' description file lead to the following syntax error: ```invalid keyword(s): 'import' ```.

It would be very convenient to be able to do so when a large number of sources are used (eg lots of globals) and/or when the writing of the description file(s) is automated.

**Comment by gdementen** [comment]
If by description file, you mean the file necessary to import .csv files into .h5, I would rather implement #125, which would in effect do what you want.
