### ISSUE TITLE
Add support for numpy transpose

### ISSUE THREAD

**Issue by benbel** [liam2/liam2#246]
It would be quite useful to be able to transpose global arrays.

This is very simple to implement, one needs to add:
````
class Transpose(NumpyChangeArray):
    np_func = np.transpose
````
and 

````
functions = { ...
    'load': Load,
    'transpose': Transpose
}
````

to `exprmisc.py`.

**Comment by gdementen** [comment]
See my comment at:
https://github.com/liam2/liam2/pull/247#issuecomment-355010784
