### ISSUE TITLE
Extexpr fails when several dimensions have the same labels

### ISSUE THREAD

**Issue by benbel** [liam2/liam2#277]
See [this discussion](https://groups.google.com/forum/#!topic/liam2-users/ufWhFgHIzRs):
```
The problem is that it currently matches axes of the "extexpr array" with the variables of your entity based on the values they have. This is both inefficient and leads to a problem if some labels are the same on several axes, like in your case the a and b axes both have True and False values.
```

**Comment by gdementen** [comment]
I usually do not open issues for issues that I know about and are not in a release...

**Comment by benbel** [comment]
Ok, my bad. Feel free to delete it.

**Comment by gdementen** [comment]
Well it does not hurt to have it in the unlikely case somebody else stumbles on that

**Comment by gdementen** [comment]
This is now fixed. Now that I read my comment back, it might have sounded rude/offensive. Sorry about this. I was just trying to explain why I didn't open an issue in the first place.
