### ISSUE TITLE
Functions ending by 'if' lead to parsing errors

### ISSUE THREAD

**Issue by benbel** [liam2/liam2#280]
A function cannot end with "if", eg
```
salaire_relatif():
  - return salaire/avg(salaire)
test():
  - test_var: salaire_relatif()
```
leads to
```
ERROR: name 'salaire_relatwhere' is not defined
while parsing: salaire_relatif()
```

This errors happens on the current master and with the 12.0 bundle.

**Comment by gdementen** [comment]
Oops. That's really a stupid mistake, but it should be easy to fix.

**Comment by gdementen** [comment]
@benjello https://github.com/liam2/liam2/blob/master/liam2/exprtools.py#L320
