### ISSUE TITLE
import error in main.py

### ISSUE THREAD

**Issue by goatchurchprime** [liam2/liam2#289]
This line: 
   https://github.com/liam2/liam2/blob/master/liam2/main.py#L41

Needs changing from:
`from version import __version__`

to:

`from liam2.version import __version__`

**Comment by gdementen** [comment]
Thanks for reporting. In fact, I already fixed that in the "qtpy" branch. I will try to merge it to master "soon" (hopefully tomorrow).

**Comment by benjello** [comment]
This is fixed in #291
