### ISSUE TITLE
How to install de new LIAM2 version on Mac or Linux?

### ISSUE THREAD

**Issue by sbacelar** [liam2/liam2#299]

**Comment by gdementen** [comment]
what do you call the new version? 0.12 or the upcoming 0.13?

**Comment by sbacelar** [comment]
0.12.

**Comment by gdementen** [comment]
If you have a working earlier version, just follow the instructions at:
http://liam2.plan.be/documentation/0.12/install.html#install-liam2-itself-from-source
If anything is unclear, ask your question here or on the mailing list.

**Comment by sbacelar** [comment]
I follow your suggestions without difficulties. I have created a `python2` environment within `Anaconda` and followed the `liam2` documentation. The only problem I had was with launching `ViTables` which gave me an error "no module named PyQt4". To view the input and output simulation databases I have installed on my Mac the `HDF5 viewer`. I hope that `liam2` will use `python3` in the next version.

**Comment by gdementen** [comment]
0.13 will support both Python 2 and Python 3 (it is already the case in the
development version). However, I cannot make any promise as to when that
version will be released...

**Comment by benjello** [comment]
@gdementen : may it is time to have a pip installable package for liam2 that works out of the box. 
The problem right now is that as it is written, `setup.py` needs Cython even before it has the opportunity to install it.

**Comment by gdementen** [comment]
I don't think this issue requires any further work.
