### ISSUE TITLE
Allow import in import.yml file

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#302]
When sharing an import file on several platforms it may be very useful to adjust only some paths. 
It is now impossible of importing other YAML import files from an YAML import file but I could be very helpful to address that particular need.

**Comment by gdementen** [comment]
This is a good idea, but given how time-constrained I am and the fact I am going to deprecate import files some time in the future (see #125), I will not fix this. That said, if you want to make a PR for this (it should be relatively easy to copy what is done for simulations), I would happily merge it.

**Comment by benjello** [comment]
Fixed by #304
