### ISSUE TITLE
link in while loop

### ISSUE THREAD

**Issue by TomasMiklosovic** [liam2/liam2#305]
Hi, I would like to ask how I can manage dummy variables in while loop. I have 15 dummy variables with names: dummy1q1, dummy1q2, dummy1q3, dummy2q1, dummy2q2,...dummy5q2 and dummy5q3.
I would like change values in while loop. I tried:
  - i: i=1
  - while i<=5:
        - j: j=1
        - while j<=3:
              - dummy[i]q[j]: if(condition, False, dummy[i]q[j])
              - j: j+1
         - i: i+1
LIAM 2 said:
SYNTAX ERROR: invalid syntax
where(condition, False, dummy[i]q[j])
How can I fix it?

Thanks.

**Comment by gdementen** [comment]
See my reply to your question on the mailing list:
https://groups.google.com/d/msg/liam2-users/6EPn2e6NI_Q/6GxZkPFiDQAJ
