### ISSUE TITLE
improve error message for bogus yaml file

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#313]
I get this very strange error message (version 0.12.0)
```
File "/home/mbenjelloul/openfisca/liam2/liam2/simulation.py", line 90, in handle_imports
    import_fields = [d.items()[0] for d in import_fields]
TypeError: 'NoneType' object is not iterable
```
I think I have a global or a field missing in my data but I would like to know which one it is and a clearer message could be helpful.

**Comment by gdementen** [comment]
I **suspect/guess** this is not a missing field, but something else breaking the yaml structure. For example, are your imported fields at the correct indentation level? Somehow import_fields is None instead of a list of dict, like it should be. A better error message in that case would help nevertheless 😉

**Comment by benjello** [comment]
You are right, the YAML file was bogus. Should I close this issue ?

**Comment by gdementen** [comment]
I would rather not. Even though it's not a missing field, it is nevertheless a case where a better error message would help. Can you produce a **minimal** example reproducing the above error message?

**Comment by benjello** [comment]
When trying to reproduce (because I fixed it ...) on master branch I got:
```python
raise Exception("invalid structure for '%s': it should be a list and it is a %s" % (context, typename(l)))
Exception: invalid structure for 'entities -> person -> fields': it should be a list and it is a NoneType
```
So it seems to be fixed. I am closing this issue. Sorry for the noise.
