### ISSUE TITLE
Check while loop

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#314]
I have been fooled several time by a while conditio that looks like:
````yaml
- while(condition):
  - do_something()
````
It is not executed and do not produce error.
At least in version 0.12.0
It is wotrh testing on master branch and prevent it to happen agian if needed.

**Comment by gdementen** [comment]
No need to check master, I can tell you there is no change in that regard. It should be an easy fix though. Simply change the lines at:
https://github.com/liam2/liam2/blob/master/liam2/entities.py#L295
and
https://github.com/liam2/liam2/blob/master/liam2/entities.py#L535

**Comment by gdementen** [comment]
to be clear, the goal is to allow that syntax. I guess replacing the startswith call with a regex would solve  the problem easily. Something like (untested!): re.match("while[ (].*", k)
