### ISSUE TITLE
Broken links in the doc

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#325]
As this one: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.negative_binomial.html
which can be found here:
https://liam2.plan.be/documentation/0.12/processes.html?highlight=binomial

**Comment by gdementen** [comment]
Thanks for the issue. Would it be too much to ask for a patch? Every little bit helps 😉.

**Comment by benjello** [comment]
Seems that the link to the numpy reference doc is broken.
What about using the latest numpy version reference doc https://numpy.org/doc/1.18/reference/index.html  ? 
Or do you prefer another version ?

**Comment by gdementen** [comment]
The goal is to keep those links valid for as long as possible so I wish there was a link to the "latest stable version" like I previously used, but I can no longer find such a link... I am also a bit nervous about linking to the "development version", so I guess release 1.18 is indeed the best we can do.

**Comment by gdementen** [comment]
fixed by #327
