### ISSUE TITLE
foreach function

### ISSUE THREAD

**Issue by RiccardoContiSogei** [liam2/liam2#326]
Hi,
I am not sure whether a workaround is already in place for this. In case it is not, would it be possible to develop within Liam2 a function like the 'foreach' available in Stata?

Es. (Stata code)

global pens_type "old_age disab survival"
foreach c of global pens_type {
gen pens_`c'=mont_`c'*coef_`c'
}

Thanks,
Riccardo

**Comment by gdementen** [comment]
There is no documented workaround for this. 

In some cases, you can workaround it by using the undocumented array() command to store those fields, but I wouldn't recommend doing this with version 0.12, as that will be incompatible with version 0.13 which should **hopefully** be released within a few months.

In other words, there is no good solution to this currently, but there will be some day, even though that will not be using some "generated variable names" mechanism. Don't hold your breath though as it will take months or even years to come.

**Comment by RiccardoContiSogei** [comment]
Thank you Gaetan!
